# Generated by Django 3.0 on 2021-04-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylechangeapp', '0003_auto_20210408_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StyleImage',
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='style_image',
        ),
    ]
